export const PROJECTS_FETCH_START = 'PROJECTS_FETCH_START';
export const PROJECTS_FETCH_SUCCESS = 'PROJECTS_FETCH_SUCCESS';
export const PROJECTS_FETCH_FAIL = 'PROJECTS_FETCH_FAIL';

export const VACANCY_ADD_START = 'VACANCY_ADD_START';
export const VACANCY_ADD_SUCCESS = 'VACANCY_ADD_SUCCESS';
export const VACANCY_ADD_FAIL = 'VACANCY_ADD_FAIL';

export const VACANCY_DELETE_START = 'VACANCY_DELETE_START';
export const VACANCY_DELETE_SUCCESS = 'VACANCY_DELETE_SUCCESS';
export const VACANCY_DELETE_FAIL = 'VACANCY_DELETE_FAIL';
