export const PROJECTS_FETCH_START = 'PROJECTS_FETCH_START';
export const PROJECTS_FETCH_SUCCESS = 'PROJECTS_FETCH_SUCCESS';
export const PROJECTS_FETCH_FAIL = 'PROJECTS_FETCH_FAIL';

export const PROJECTS_ADD_START = 'PROJECTS_ADD_START';
export const PROJECTS_ADD_SUCCESS = 'PROJECTS_ADD_SUCCESS';
export const PROJECTS_ADD_CLOSE = 'PROJECTS_ADD_CLOSE';

export const PROJECTS_TOGGLE_VACANCIES = 'PROJECTS_TOGGLE_VACANCIES';

export const VACANCY_ADD_START = 'VACANCY_ADD_START';
export const VACANCY_ADD_SUCCESS = 'VACANCY_ADD_SUCCESS';
export const VACANCY_ADD_FAIL = 'VACANCY_ADD_FAIL';

export const VACANCY_DELETE_START = 'VACANCY_DELETE_START';
export const VACANCY_DELETE_SUCCESS = 'VACANCY_DELETE_SUCCESS';
export const VACANCY_DELETE_FAIL = 'VACANCY_DELETE_FAIL';

export const VACANCY_TOGGLE_START = 'VACANCY_TOGGLE_START';
export const VACANCY_TOGGLE_SUCCESS = 'VACANCY_TOGGLE_SUCCESS';
export const VACANCY_TOGGLE_FAIL = 'VACANCY_TOGGLE_FAIL';
